export const ROUTES = {
  HOME: "/",
  LOGIN: "/login",
  SIGNUP: "/signup",
  FORGOT_PASSWORD: "/forgot-password",
  DASHBOARD: "/dashboard",
  TRIPS: "/trips",
  CREATE_TRIP: "/trips/new",
  TRIP_DETAILS: "/trips/:tripId",
  DISCOVER: "/discover",
  ITINERARY: "/itinerary",
  BUDGET: "/budget",
  CHECKLIST: "/checklist",
  ACTIVITIES: "/activities",
  NOTES: "/notes",
  PROFILE: "/profile",
  SETTINGS: "/settings",
  ADMIN: "/admin",
  SHARED_ITINERARY: "/share/:shareId",
};
