"""Add cities, attractions and itinerary templates

Revision ID: 38bdefcf56d0
Revises: fd4969996e26
Create Date: 2026-05-10 15:52:57.887446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38bdefcf56d0'
down_revision = 'fd4969996e26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('country', sa.String(length=120), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('popularity_score', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cities_name'), ['name'], unique=True)

    op.create_table('attractions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category_tags', sa.String(length=500), nullable=True),
    sa.Column('popularity_score', sa.Integer(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('attractions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attractions_city_id'), ['city_id'], unique=False)

    op.create_table('itinerary_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('days', sa.Integer(), nullable=False),
    sa.Column('travel_type', sa.String(length=50), nullable=False),
    sa.Column('itinerary_data', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('itinerary_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_itinerary_templates_city_id'), ['city_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('itinerary_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_itinerary_templates_city_id'))

    op.drop_table('itinerary_templates')
    with op.batch_alter_table('attractions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attractions_city_id'))

    op.drop_table('attractions')
    with op.batch_alter_table('cities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cities_name'))

    op.drop_table('cities')
    # ### end Alembic commands ###
